# Generated by Django 4.0 on 2022-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talents',
            fields=[
                ('TalentId', models.AutoField(primary_key=True, serialize=False)),
                ('TalentName', models.CharField(max_length=500)),
            ],
        ),
    ]
